version: '3'

services:
  ldap:
    image: osixia/openldap:latest
    ports:
      - 389:389
      - 636:636
  app:
    image: httpd:latest
    volumes:
      - ./config/app/usr/local/apache2/htdocs:/usr/local/apache2/htdocs
#    ports:
#      - 7000:80
  app2:
    image: httpd:latest
    volumes:
      - ./config/app/usr/local/apache2/htdocs2:/usr/local/apache2/htdocs
#    ports:
#      - 7000:80
  httpd:
    image: httpd:latest
    volumes:
      - ./config/httpd/usr/local/apache2/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./config/httpd/usr/local/apache2/conf/extra/proxy-html.conf:/usr/local/apache2/conf/extra/proxy-html.conf
    environment:
      - PROXY_TARGET_HOST=app
      - PROXY_TARGET_PORT=80
      - PROXY_LDAP_URL=ldap://ldap/dc=example,dc=org?uid?sub?(objectClass=posixAccount)
    ports:
      - 7001:7001
      - 7002:7002
    links:
      - app:app
      - app2:app2
      - ldap:ldap
    depends_on:
      - ldap
      - app