version: '3'

services:
  ldap:
    image: dinkel/openldap:latest
    command: slapd -d -1 -u openldap -g openldap
    ports:
      - 389:389
    environment:
      - SLAPD_PASSWORD=admin
      - SLAPD_DOMAIN=example.org
      - SLAPD_ORGANIZATION=Example Inc.
    volumes:
      - ./config/ldap/ldif:/etc/ldap.dist/prepopulate
  app:
    image: eizoflexscan/euler3:latest
    ports:
      - 5858:5858
    volumes:
      - ./config/app/usr/local/apache2/htdocs:/usr/local/apache2/htdocs
  httpd:
    image: httpd:latest
    ports:
      - 5959:5959
    volumes:
      - ./config/httpd/usr/local/apache2/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./config/httpd/usr/local/apache2/conf/extra/proxy-html.conf:/usr/local/apache2/conf/extra/proxy-html.conf
    links:
      - app:app
    depends_on:
      - ldap
      - app